# cargo-about configuration: `cargo about generate --locked about.hbs -o THIRD-PARTY-LICENSES`.
# The release workflow ships the result with every package. Keep `accepted`
# in step with [licenses] allow in deny.toml.
accepted = [
    "MIT",
    "Apache-2.0",
    "Apache-2.0 WITH LLVM-exception",
    "BSD-2-Clause",
    "BSD-3-Clause",
    "ISC",
    "Unicode-3.0",
    "Zlib",
    "MPL-2.0",
    "Unlicense",
    "CC0-1.0",
    "CDLA-Permissive-2.0",
    "LicenseRef-Slint-Royalty-free-2.0",
    "LicenseRef-Slint-Software-3.0",
]
targets = ["x86_64-unknown-linux-gnu", "aarch64-unknown-linux-gnu"]
ignore-build-dependencies = true
ignore-dev-dependencies = true
