[package]
name = "ricercar-audio"
version = "0.3.0"
edition = "2024"
license.workspace = true

[dependencies]
alsa = "0.12.1"
crossbeam-channel.workspace = true
symphonia = { version = "0.6.1", default-features = false, features = ["mp3", "flac", "vorbis", "ogg", "wav", "aiff", "isomp4", "aac", "alac", "pcm", "adpcm"] }
thiserror.workspace = true
tracing.workspace = true
ureq = "2.12"
