[package]
name = "ricercar-ui"
version = "0.1.0"
edition = "2024"
license.workspace = true

[dependencies]
image = "0.25.10"
ricercar-audio = { version = "0.1.0", path = "../ricercar-audio" }
ricercar-core.workspace = true
ricercar-daemon = { version = "0.1.0", path = "../ricercar-daemon" }
ricercar-mpris.workspace = true
ricercar-upnp.workspace = true
slint = "1.18.1"
thiserror.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true

[build-dependencies]
slint-build = "1.18.1"
