[package]
name = "ricercar-daemon"
version = "0.5.2"
edition = "2024"
license.workspace = true
rust-version.workspace = true

[dependencies]
ctrlc = { version = "3.5.2", features = ["termination"] }
ricercar-audio = { version = "0.5.2", path = "../ricercar-audio" }
ricercar-core.workspace = true
ricercar-online.workspace = true
ricercar-mpris.workspace = true
ricercar-upnp.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
toml = "1.1.6"
zbus = "5.19.0"

[dev-dependencies]
tempfile = "3.27.0"
